[workspace]
members = [
  "classifier",
  "core-types",
  "data-client",
  "flatfile-source",
  "metrics",
  "nbbo-cache",
  "orchestrator",
  "replayer",
  "rest-source",
  "storage",
  "tui",
  "ws-source"
]
