[ws]

[staleness]

[classifier]

[greeks]

[storage]

[rest]

[scheduler]

[flatfile]
date_ranges = [
  { start_ts = "2025-11-01T00:00:00Z", end_ts = "2025-11-05T00:00:00Z" },
  { start_ts = "2025-11-05T00:00:00Z" },
]
polygonio_key = "Th9_z6vvF2DGtaPKr_ybOkW8YXTxRGfb"
polygonio_access_key_id = "5fb15c64-1e85-4ad3-85b2-8b6611857710"
polygonio_secret_access_key = "VxpNfHd6aiZGn6BSy0cXgM3d9BoKPQoE"
