[package]
name = "data-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
core-types = { path = "../core-types" }
flatfile-source = { path = "../flatfile-source" }
futures = "0.3"
tokio-stream = "0.1"
