[package]
name = "flatfile-source"
version = "0.1.0"
edition = "2021"

[dependencies]
core-types = { path = "../core-types" }
futures = "0.3.31"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
bytes = "1.0"
async-compression = { version = "0.4", features = ["gzip", "tokio"] }
tokio-util = { version = "0.7", features = ["io"] }
flate2 = "1.1.5"
csv = "1.4.0"
tokio-stream = "0.1.17"
